import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-image-generation',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './image-generation.component.html',
  styleUrl: './image-generation.component.scss'
})
export class ImageGenerationComponent {
   window = window;

  experts = [
    {
      name: 'Ideogram',
      role: 'AI image generator with a focus on text-to-image and typography.',
      image: 'assets/images/image-generation/Ideogram-logo.jpg',
      rating: 4.5,
      link: 'Go To Site →',
      url: 'https://ideogram.ai/',
    },
    {
      name: 'DreamStudio',
      role: 'Official platform for Stable Diffusion image generation.',
      image: 'assets/images/image-generation/dreamstudio-logo.png',
      rating: 4.6,
      link: 'Go To Site →',
      url: 'https://dreamstudio.ai/',
    },
    {
      name: 'Stable Diffusion',
      role: 'Open-source text-to-image diffusion model.',
      image: 'assets/images/image-generation/stable-diffusion.png',
      rating: 4.8,
      link: 'Go To Site →',
      url: 'https://stability.ai/stable-diffusion',
    },
    {
      name: 'Midjourney',
      role: 'Popular AI art generator with a focus on creative and artistic images.',
      image: 'assets/images/image-generation/midjourney-logo.jpg',
      rating: 4.9,
      link: 'Go To Site →',
      url: 'https://www.midjourney.com/',
    },
    {
      name: 'DALL·E',
      role: 'OpenAI’s advanced text-to-image generator.',
      image: 'assets/images/image-generation/dalle-logo.png',
      rating: 4.7,
      link: 'Go To Site →',
      url: 'https://labs.openai.com/',
    },
    {
      name: 'Adobe Firefly',
      role: 'Adobe’s suite of generative AI tools for creative projects.',
      image: 'assets/images/image-generation/adobe-firefly-logo.jpg',
      rating: 4.6,
      link: 'Go To Site →',
      url: 'https://firefly.adobe.com/',
    },
    {
      name: 'Leonardo AI',
      role: 'AI-powered platform for generating high-quality images and assets.',
      image: 'assets/images/image-generation/leonardo-logo.jpg',
      rating: 4.5,
      link: 'Go To Site →',
      url: 'https://leonardo.ai/',
    },
    {
      name: 'BlueWillow',
      role: 'AI-powered image generator for creative and commercial use.',
      image: 'assets/images/image-generation/blue-willow-logo.png',
      rating: 4.3,
      link: 'Go To Site →',
      url: 'https://www.bluewillow.ai/',
    },
    {
      name: 'Craiyon (formerly DALL·E Mini)',
      role: 'Free online AI image generator from text prompts.',
      image: 'assets/images/image-generation/craiyon-logo.png',
      rating: 4.2,
      link: 'Go To Site →',
      url: 'https://www.craiyon.com/',
    },
    {
      name: 'NightCafe',
      role: 'Popular AI art generator with multiple algorithms and community features.',
      image: 'assets/images/image-generation/nightcafe-logo.jpeg',
      rating: 4.4,
      link: 'Go To Site →',
      url: 'https://creator.nightcafe.studio/',
    },
    {
      name: 'Artbreeder',
      role: 'Collaborative AI art platform for blending and evolving images.',
      image: 'assets/images/image-generation/artbreeder-logo.png',
      rating: 4.1,
      link: 'Go To Site →',
      url: 'https://www.artbreeder.com/',
    },
    {
      name: 'Deep Dream Generator',
      role: 'AI-powered tool for creating dream-like, surreal images.',
      image: 'assets/images/image-generation/Deep_Dream_Generator-logo.png',
      rating: 4.0,
      link: 'Go To Site →',
      url: 'https://deepdreamgenerator.com/',
    },
    {
      name: 'Fotor AI Image Generator',
      role: 'Online AI image generator for art, avatars, and more.',
      image: 'assets/images/image-generation/fotor-logo.png',
      rating: 4.0,
      link: 'Go To Site →',
      url: 'https://www.fotor.com/features/ai-image-generator/',
    },
    {
      name: 'Picsart AI Image Generator',
      role: 'AI-powered creative suite with text-to-image and editing tools.',
      image: 'assets/images/image-generation/picsart-logo.png',
      rating: 4.2,
      link: 'Go To Site →',
      url: 'https://picsart.com/ai-image-generator',
    },
    {
      name: 'Playground AI',
      role: 'Free-to-use AI image generator with advanced editing features.',
      image: 'assets/images/image-generation/playground-logo.png',
      rating: 4.3,
      link: 'Go To Site →',
      url: 'https://playgroundai.com/',
    },
    {
      name: 'StarryAI',
      role: 'AI art generator for unique, high-quality images from text.',
      image: 'assets/images/image-generation/starryai-logo.jpg',
      rating: 4.1,
      link: 'Go To Site →',
      url: 'https://www.starryai.com/',
    },
    {
      name: 'RunwayML',
      role: 'Creative AI suite for image, video, and generative design.',
      image: 'assets/images/image-generation/runway-ml-logo.jpg',
      rating: 4.4,
      link: 'Go To Site →',
      url: 'https://runwayml.com/',
    },
    {
      name: 'Dream by WOMBO',
      role: 'Mobile app for AI-powered art generation from text prompts.',
      image: 'assets/images/image-generation/wombo-logo.jpg',
      rating: 4.5,
      link: 'Go To Site →',
      url: 'https://www.wombo.art/',
    },
    {
      name: 'Stablecog',
      role: 'Open-source AI image generator with Stable Diffusion.',
      image: 'assets/images/image-generation/stablecog-logo.png',
      rating: 4.0,
      link: 'Go To Site →',
      url: 'https://stablecog.com/',
    },
    {
      name: 'Mage.Space',
      role: 'Free AI art generator using Stable Diffusion models.',
      image: 'assets/images/image-generation/MageAI-logo.png',
      rating: 4.1,
      link: 'Go To Site →',
      url: 'https://www.mage.space/',
    },
    {
      name: 'Lexica',
      role: 'AI image search and generation platform using Stable Diffusion.',
      image: 'assets/images/image-generation/lexica-logo.png',
      rating: 4.2,
      link: 'Go To Site →',
      url: 'https://lexica.art/',
    },
  ];
}
